### ISSUE TITLE
Hexo博客搭建

### ISSUE THREAD

**Issue by VizzAwo** [VizzAwo/blog#4]
> 声明：本文中涉及命令行中，以`<>`包含的，则为必选项；以`[]`包含的则是可选项

### 安装Git

- Windows：下载&安装[git](https://git-scm.com/download/)
- Linux (Ubuntu, Debian)： `sudo apt install git`
- Linux (Fedora, Red Hat, CentOS)： `sudo yum install git`
- Linux (Arch 系列)： `sudo pacman -S git`

### 安装Nodejs

- 使用nvm安装：
  - Windows：见[nvm-windows](https://github.com/coreybutler/nvm-windows)
  - Linux: 见[nvm](https://github.com/nvm-sh/nvm)

- 使用安装程序安装：[Nodejs](https://nodejs.org/en/)

### 安装Hexo

在安装Nodejs后，使用npm安装hexo

```bash
npm install -g hexo-cli
```

### 建立 & 初始化博客目录

```bash
mkdir <your_blog_name> #建立博客目录，<your_blog_name>自行替换为合适的名称
hexo init <your_blog_name> #初始化博客目录
```

### 配置Hexo

在初始化完成之后，输入`cd <your_blog_name>`进入博客目录

输入`ls`指令，可见`_config.yml`文件，有关博客的基础配置，都需要通过修改这个文件中的内容达成

#### 站点

```yaml
# Site
title:
subtitle:
description:
keywords:
author:
language:
timezone:
```

| 参数          | 描述                                                         |
| ------------- | ------------------------------------------------------------ |
| `title`       | 网站标题                                                     |
| `subtitle`    | 网站副标题                                                   |
| `description` | 网站描述                                                     |
| `keywords`    | 网站关键词                                                   |
| `author`      | 作者名字                                                     |
| `language`    | 网站使用的语言                                               |
| `timezone`    | 网站时区：详见[时区列表](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) |

#### URL

```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url:
root:
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailiing_index: true
```

| 参数                         | 描述                                                      |
| ---------------------------- | --------------------------------------------------------- |
| `url`                        | 网址                                                      |
| `root`                       | 网站根目录                                                |
| `permalink`                  | 文章的永久链接格式                                        |
| `permalink_defaults`         | 永久链接中各部分的默认值                                  |
| `pretty_urls`                | 改写 `permalink` 的值来美化 URL                           |
| `pretty_urls.trailing_index` | 是否在永久链接中保留尾部的 `index.html` ， `false` 时去除 |

> 提醒
>
> 如果你的网站在子目录中，如： `https://yoursite.com/blog` ，就把你的 `url` 设为 `http://yoursite.com/blog` 并把 `root` 设为 `/blog/` 。

例如：

```yaml
# 比如，一个页面的永久链接是 http://example.com/foo/bar/index.html
pretty_urls:
  trailing_index: false
# 此时页面的永久链接会变为 http://example.com/foo/bar/
```

#### 目录

```yaml
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md
```

| 参数           | 描述                                                         |
| -------------- | ------------------------------------------------------------ |
| `source_dir`   | 资源文件夹                                                   |
| `public_dir`   | 公共文件夹                                                   |
| `tag_dir`      | 标签文件夹                                                   |
| `archive_dir`  | 归档文件夹                                                   |
| `category_dir` | 分类文件夹                                                   |
| `code_dir`     | Include code 文件夹                                          |
| `i18n_dir`     | 国际化文件夹                                                 |
| `skip_render`  | 跳过文件的渲染。匹配到的文件将直接复制到 `public` 目录中。您可使用 [glob (opens new window)](https://github.com/micromatch/micromatch#extended-globbing)表达式来匹配路径。 |

> 提醒
>
> 一般情况下，这部分是不需要修改的。

例如：

```yaml
skip_render: "mypage/**/*"
# 将会直接将 `source/mypage/index.html` 和 `source/mypage/code.js` 不做改动地输出到 'public' 目录
# 你也可以用这种方法来跳过对指定文章文件的渲染
skip_render: "_posts/test-post.md"
# 这将会忽略对 'test-post.md' 的渲染
```

#### 文章

```yaml
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
```

| 参数                    | 描述                                                         |
| ----------------------- | ------------------------------------------------------------ |
| `new_post_name`         | 新文章的文件名称                                             |
| `default_layout`        | 预设布局                                                     |
| `auto_spacing`          | 在中文和英文之间加入空格                                     |
| `titlecase`             | 把标题转换为 title case                                      |
| `external_link`         | 在新标签中打开链接                                           |
| `external_link.enable`  | 在新标签中打开链接                                           |
| `external_link.field`   | 适用于整个网站或仅文章                                       |
| `external_link.exclude` | 排除主机名。在适用时指定子域，包括 `www`                     |
| `filename_case`         | 把文件名称转换为 (1) 小写或 (2) 大写                         |
| `render_drafts`         | 显示草稿                                                     |
| `post_asset_folder`     | 启动 [Asset 文件夹(opens new window)](https://hexo.io/zh-cn/docs/asset-folders) |
| `relative_link`         | 把链接改为与根目录的相对位址                                 |
| `future`                | 显示未来的文章                                               |
| `highlight`             | 代码块的设置                                                 |
| `highlight.enable`      | 开启语法高亮                                                 |
| `highlight.auto_detect` | 如果未指定语言，则启用自动检测                               |
| `highlight.line_number` | 显示行数                                                     |
| `highlight.tab_replace` | 用 n 个空格替换 tabs；如果值为空，则不会替换 tabs            |

#### 分类 & 标签

```yaml
# Category & Tag
default_category: uncategorized
category_map:
tag_map:
```

| 参数               | 描述     |
| ------------------ | -------- |
| `default_category` | 默认分类 |
| `category_map`     | 分类别名 |
| `tag_map`          | 标签别名 |

#### 日期 / 时间格式

```yaml
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
use_date_for_updated: true
```

| 参数                   | 描述                                                         |
| ---------------------- | ------------------------------------------------------------ |
| `date_format`          | 日期格式                                                     |
| `time_format`          | 时间格式                                                     |
| `use_date_for_updated` | 如果前面没有提供更新日期，则使用 `post.updated` 中的发布日期。通常与 Git 工作流一起使用。 |

> 提醒
>
> Hexo 使用 [Moment.js](http://momentjs.com/)来解析和显示时间。

#### 分页

```yaml
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
```

| 参数             | 描述                                |
| ---------------- | ----------------------------------- |
| `per_page`       | 每页显示的文章量 (0 = 关闭分页功能) |
| `pagination_dir` | 分页目录                            |

#### 扩展

```yaml
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme:
theme_config:
deploy:
meta_generator:
```

| 参数             | 描述                                                         |
| ---------------- | ------------------------------------------------------------ |
| `theme`          | 当前主题名称。值为 `false` 时禁用主题                        |
| `theme_config`   | 主题的配置文件。在这里放置的配置会覆盖主题目录下的 `_config.yml` 中的配置。 |
| `deploy`         | 部署的设置                                                   |
| `meta_generator` | [Meta generator](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/meta#属性)标签。 值为 `false` 时 Hexo 不会在头部插入该标签。 |

### Hexo主题安装

- 主题下载：[Hexo themes](https://hexo.io/themes/)

选择自己喜欢的博客主题，下载后，自行查阅该主题文档进行配置。（通常情况下，每个主题都附有使用文档）

### Hexo基础命令

- `hexo init [directory]`：初始化指定目录，不指定则默认为当前目录
- `hexo new [layout] <title>`：layout可以是页面(page)也可以是文章(post)，不声明的情况下，默认创建文章
  - `hexo new page 404`：创建一个404页面
  - `hexo new post 2021-年度总结`：创建一篇名为《2021-年度总结》的文章
  - `hexo new 2021-年度总结`：同上 
- `hexo server`：一切就绪，可使用该命令在本地预览网站
- `hexo generate`：生成静态页面
- `hexo deploy`：部署网站到指定位置（可以是GIthub、也可以是自己的服务器.....）
- `hexo clean`：清空由`hexo generate`命令生成的文件
- `hexo version`：查看当前hexo版本号

#### 准备工作

1. 如果没有Github账户，点此[GitHub](https://github.com)前往注册
2. 建立一个公开的仓库，仓库名格式为`your_name.github.io`
3. 之后，记下该仓库的ssh地址，格式为`git@github.com:your_name/your_name.github.io.git`
4. [添加ssh密钥到Github](#添加ssh密钥到Github)

#### 添加ssh密钥到Github

1. 使用`ssh-keygen`生成ssh密钥
2. 在用户主目录使用`cat .ssh/id_rsa.pub`查看公钥，而后复制
3. 添加公钥到Github：[New SSh key](https://github.com/settings/ssh/new)

#### 安装部署插件

```bash
npm install hexo-deployer-git --save
npm install hexo-server --save
```

### 配置Git

设置你的用户名 & 邮箱

```bash
git config --global user.name "Your_user_name"
git config --global user.email Your_email@example.com
```

### 配置站点 `_config.yml` 文件

在`_config.yml`末尾添加

```yaml
deploy:
  type: git # 类型填git
  repo: <repository url> # 你的Github仓库地址
  branch: master # 分支名称。默认填写 master 如果您使用的是 GitHub ，程序会尝试自动检测。
  message: # 提交信息可以自定义，不填的则默认为提交时间
```

### 发布到 GitHub

在本地的 Hexo 站点根目录下，执行如下命令即可部署到 GitHub Pages 上

```bash
hexo clean && hexo d -g
```

至此，便能在浏览器地址栏输入`your_name.github.io`访问到博客网站

### 自定义域名

1. 如果你拥有个人域名，请用 A 记录解析到以下 IP 中的任意一个。如果使用 CNAME 请解析到你的 GitHub 仓库名称。

   **参考表格**

| 记录类型 | 主机记录 | 解析路线 |       记录值        | MAX 优先级 | TTL（秒） |
| :------: | :------: | :------: | :-----------------: | :--------: | :-------: |
|  CNAME   |   www    |   默认   | GitHub 博客仓库名称 |     -      |    600    |
|  CNAME   |    @     |   默认   | GitHub 博客仓库名称 |     -      |    600    |

2. 打开仓库设置，找到 GitHub Pages 项目，修改 Custom domain 选项的值为你的自定义域名（不带 http 等前缀）
3. 勾选 Custom domain 选项下的 Enforce HTTPS 选项，强制开启 Https 。如果遇到 `Enforce HTTPS` 选项无法打开，可以稍等一会儿再尝试。

> 提醒
>
> 同时需要在本地的 `source` 目录新建一个 CNAME 文件，内容为你的自定义域名（不带 http 等前缀）。否则无法使用自定义域名功能（ `hexo d` 生成的文件没有 CNAME 文件，导致仓库的自定域名设置失效）

---

## 参考资料

1. [Hexo Official](https://hexo.io)
2. [EasyHexo](https://easyhexo.com/)
